In [17]:
import numpy as np
import math
import matplotlib.pyplot as mpl
from sympy import *
x1, x2, x3, x4, x5 = symbols('x1, x2, x3, x4, x5')


In [20]:
linha_1 = [1, 1, 1, 0, 2]
linha_2 = [0, 1, 2, 1, 1]
linha_3 = [0, 0, 1, 2, 1]
linha_4 = [0, 0, 0, 2, 1]
linha_5 = [0, 0, 0, 0, 10]

matriz = Matrix([linha_1, linha_2, linha_3, linha_4, linha_5])
matriz

Matrix([
[1, 1, 1, 0,  2],
[0, 1, 2, 1,  1],
[0, 0, 1, 2,  1],
[0, 0, 0, 2,  1],
[0, 0, 0, 0, 10]])

In [19]:
linha_x = Matrix([[x1],[x2],[x3],[x4],[x5]])
linha_x

Matrix([
[x1],
[x2],
[x3],
[x4],
[x5]])

In [21]:
linha_r = Matrix([[1],[2],[-2],[-4],[-20]])
linha_r

Matrix([
[  1],
[  2],
[ -2],
[ -4],
[-20]])

In [26]:
solve(Eq(matriz * linha_x , linha_r), [x1, x2, x3, x4, x5])

{x1: 2, x2: 1, x3: 2, x4: -1, x5: -2}

In [27]:
linha_1 = [2, 1, 3, 4]
linha_2 = [1, 4, 2, 1]
linha_3 = [3, 2, 1, 4]
linha_4 = [2, 2, 3, 1]

matriz = Matrix([linha_1, linha_2, linha_3, linha_4])
matriz

Matrix([
[2, 1, 3, 4],
[1, 4, 2, 1],
[3, 2, 1, 4],
[2, 2, 3, 1]])

In [30]:
linha_x = Matrix([[x1],[x2],[x3],[x4]])
linha_x

Matrix([
[x1],
[x2],
[x3],
[x4]])

In [31]:
linha_r = Matrix([[16],[5],[11],[12]])
linha_r

Matrix([
[16],
[ 5],
[11],
[12]])

In [34]:
linha_1 = [2]

matriz_A1 = Matrix([linha_1])
matriz_A1

Matrix([[2]])

In [33]:
matriz_A1.det()

2

In [36]:
linha_1 = [2, 1]
linha_2 = [1, 4]

matriz_A2 = Matrix([linha_1, linha_2])
matriz_A2

Matrix([
[2, 1],
[1, 4]])

In [37]:
matriz_A2.det()

7

In [38]:
linha_1 = [2, 1, 3]
linha_2 = [1, 4, 2]
linha_3 = [3, 2, 1]

matriz_A3 = Matrix([linha_1, linha_2, linha_3])
matriz_A3

Matrix([
[2, 1, 3],
[1, 4, 2],
[3, 2, 1]])

In [39]:
matriz_A3.det()

-25

In [52]:
linha_1 = np.array([2, 1, 3, 4])
linha_2 = np.array([1, 4, 2, 1])
linha_3 = np.array([3, 2, 1, 4])
linha_4 = np.array([2, 2, 3, 1])

In [64]:
m21 = linha_2[0] / linha_1[0]
linha_2 = linha_2 - m21 * linha_1
linha_2

m31 = linha_3[0] / linha_1[0]
linha_3 = linha_3 - m31 * linha_1
linha_3

m41 = linha_4[0] / linha_1[0]
linha_4 = linha_4 - m41 * linha_1
linha_4

array([ 0.,  1.,  0., -3.])

In [71]:
def eliminacao(item, index, linha_pivo):
    return item - (item[index] / linha_pivo[index]) * linha_pivo
    
matrix = [linha_1, linha_2, linha_3, linha_4]

for index_pivo, linha in enumerate(matrix):
    linha = eliminacao(linha, index_pivo, matrix[index_pivo])

matrix

[array([2, 1, 3, 4]),
 array([ 0. ,  3.5,  0.5, -1. ]),
 array([ 0. ,  3.5,  0.5, -1. ]),
 array([ 0.,  1.,  0., -3.])]